### ISSUE TITLE
informationWithHeld

### ISSUE THREAD

**Issue by megbalk** [futres/fovt-data-pipeline#13]
Are we using this column to exclude data from the FuTRES API and data portal?

**Comment by jdeck88** [comment]
This field indicates that there are other columns that have NOT been made public and the purpose here is to indicate that it exists but is not presented along with the record details.  The API and processing scripts are not smart enough to parse this field and actively exclude the data... That is, the purpose here is to indicate absence of data but not to actively exclude it.

Also, If there is a project that we do not want to  make public we should mark the project as Private in GEOME.

**Comment by megbalk** [comment]
Ok! Is that private and discoverable or not discoverable?

**Comment by jdeck88** [comment]
discoverable only means that a public user can view the project metadata if the project is marked as private.
So, when marked as private, non of the data will be visible to an un-authenticated user.

**Comment by megbalk** [comment]
thanks for the clarificaiton. @nsewnath worth reading!
